# Generated by Django 4.0.5 on 2022-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_explorer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
