# Generated by Django 4.0.5 on 2022-06-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_explorer_app', '0003_remove_artist_slug_artist_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='sp_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
