# Generated by Django 4.0.5 on 2022-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_explorer_app', '0005_spotifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
