# Generated by Django 4.0.5 on 2022-06-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_explorer_app', '0007_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
