# Generated by Django 4.0.5 on 2022-06-25 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_explorer_app', '0009_artist_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='following',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
